version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:latest
    restart: always
    network_mode: bridge
    volumes:
      - telegraf-data:/etc/telegraf
   # links:
    #  - influxdb
    ports:
      - "19092:8092/udp"
      - "19094:8094"
      - "19125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: quay.io/influxdb/influxdb:nightly
    restart: always    
    network_mode: bridge
    volumes:
      - influxdb-data:/root/.influxdbv2
    ports:
      - "19086:8086"
  node-red:
    image: nodered/node-red:latest
    restart: always
    network_mode: bridge
    ports:
      - "19880:1880"
    #environment:
     # - FLOWS=flows.json
    volumes:
      - node-red-data:/data
  grafana:
    image: grafana/grafana:latest
    restart: always
    network_mode: bridge
    #links:
     # - influxdb
    ports:
      - "19300:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - portainer-data:/var/run/docker.sock
      - portainer-data:/data
  magicmirror:
    image: bastilimbach/docker-magicmirror:latest
    network_mode: bridge
    ports: 
      - "19888:8080"
#    entrypoint: "entrypoint.sh"
    volumes:
      - magicmirror-data:/opt/magic-mirror
     
  backup:
    image: futurice/docker-volume-backup
    volumes:
      - telegraf-data:/backup/telegraf-data:ro
      - influxdb-data:/backup/influxdb-data:ro
      - node-red-data:/backup/node-red-data:ro
      - grafana-data:/backup/grafana-data:ro    # Mount the Grafana data volume (as read-only)
      - magicmirror-data:/backup/magicmirror-data:ro
      - ./backups:/archive                      # Mount a local folder as the backup archive
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:

  telegraf-data:
  
  influxdb-data:

  node-red-data:

  portainer-data:

