version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:latest
    restart: always
    network_mode: bridge
    volumes:
      - /shared/telegraf:/etc/telegraf
   # links:
    #  - influxdb
    ports:
      - "19092:8092/udp"
      - "19094:8094"
      - "19125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: quay.io/influxdb/influxdb:nightly
    restart: always    
    network_mode: bridge
    volumes:
      - /shared/influxdb:/root/.influxdbv2
    ports:
      - "19086:8086"
  node-red:
    image: nodered/node-red:latest
    restart: always
    network_mode: bridge
    ports:
      - "19880:1880"
    #environment:
     # - FLOWS=flows.json
    volumes:
      - /shared/node-red:/data
  grafana:
    image: grafana/grafana:latest
    restart: always
    network_mode: bridge
    #links:
     # - influxdb
    ports:
      - "19300:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - /shared/grafana:/var/lib/grafana
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /shared/portainer/var/run/docker.sock:/var/run/docker.sock
      - /shared/portainer:/data
  magicmirror:
    image: bastilimbach/docker-magicmirror:latest
    network_mode: bridge
    ports: 
      - "19888:8080"
#    entrypoint: "entrypoint.sh"
    volumes:
      - /shared/magicmirror:/opt/magic-mirror
# Explicitly define the persistent volume for your data storage
#volumes:
 # grafana-data:

  #telegraf-data:
  
  #influxdb-data:

 # node-red-data:

  #portainer-data:

#  magicmirror:
 # magicmirror-data:
#     driver: local
 #    driver_opts:
  #     Mountpoint: /shared/magicmirror-data
